import { createRouter } from "@tanstack/react-router";
import { routeTree } from "./routeTree.gen";

// Required by the TanStack Start Vite plugin — it imports getRouter (as
// #tanstack-router-entry) to build the SSR and client entries.
// routeTree.gen.ts is generated by the plugin.
export function getRouter() {
  return createRouter({
    routeTree,
    scrollRestoration: true,
    defaultPreload: "intent",
    defaultNotFoundComponent: () => (
      <div
        style={{
          padding: "24px",
          fontFamily: "var(--mono)",
          fontSize: "12px",
          color: "var(--text-muted)",
        }}
      >
        404 — not found.{" "}
        <a href="/" style={{ color: "var(--blue)" }}>
          Go to dashboard
        </a>
      </div>
    ),
  });
}

declare module "@tanstack/react-router" {
  interface Register {
    router: ReturnType<typeof getRouter>;
  }
}
